Repository SCE-SWE-2018-G3/ticket-management-system, pull requests merged in 2018-12, with the labels that each got.

#56 Progress on ticket container
  Source Code/Ticket Management System/Ticket Management System.vcxproj
  Source Code/Ticket Management System/Ticket Management System.vcxproj.filters
  Source Code/Ticket Management System/ticket_container.c
  Source Code/Ticket Management System/ticket_container_util.c
  Source Code/Ticket Management System/ticket_container_util.h
Labels: code quality, feature

#54 Add documentation to headers
  Source Code/Ticket Management System/auth.h
  Source Code/Ticket Management System/auth_menu.h
  Source Code/Ticket Management System/customer_menu.h
  Source Code/Ticket Management System/menu.h
  Source Code/Ticket Management System/menu_option.h
  Source Code/Ticket Management System/supportgiver_menu.h
  Source Code/Ticket Management System/ticket.h
  Source Code/Ticket Management System/ticket_container.h
  Source Code/Ticket Management System/vector.h
Labels: documentation

#65 Note after updated
  Source Code/Ticket Management System/customer_menu.c
  Source Code/Ticket Management System/supportgiver_menu.c
  Source Code/Ticket Management System/ticket.c
  Source Code/Ticket Management System/ticket.h
  Source Code/Ticket Management System/ticket_container_util.c
Labels: feature

#63 Refactor support giver menu & Fix some bugs
  Source Code/Ticket Management System/menu.c
  Source Code/Ticket Management System/supportgiver_menu.c
  Source Code/Ticket Management System/ticket.c
  Source Code/Ticket Management System/vector.c
Labels: bug, code quality, requested changes

#70 input fixes, and contact details update function
  Source Code/Ticket Management System/Ticket Management System.vcxproj
  Source Code/Ticket Management System/Ticket Management System.vcxproj.filters
  Source Code/Ticket Management System/auth.c
  Source Code/Ticket Management System/auth.h
  Source Code/Ticket Management System/auth_menu.c
  Source Code/Ticket Management System/customer_menu.c
  Source Code/Ticket Management System/input_manip.c
  Source Code/Ticket Management System/input_manip.h
  Source Code/Ticket Management System/ticket.h
  Source Code/Ticket Management System/ticket_container.c
  Source Code/Ticket Management System/ticket_container_util.c
  Source Code/Ticket Management System/ticket_container_util.h
  Source Code/Ticket Management System/user.c
  Source Code/Ticket Management System/user.h
  Source Code/Ticket Management System/user_container.c
  Source Code/Ticket Management System/user_container.h
  Source Code/Ticket Management System/user_container_util.c
  Source Code/Ticket Management System/user_container_util.h
Labels: bug, feature

#75 Implement support giver BL
  Source Code/Ticket Management System/Ticket Management System.vcxproj
  Source Code/Ticket Management System/Ticket Management System.vcxproj.filters
  Source Code/Ticket Management System/auth_menu.c
  Source Code/Ticket Management System/customer_menu.c
  Source Code/Ticket Management System/menu_option.c
  Source Code/Ticket Management System/menu_option.h
  Source Code/Ticket Management System/supportgiver_menu.c
  Source Code/Ticket Management System/supportgiver_menu_util.c
  Source Code/Ticket Management System/supportgiver_menu_util.h
  Source Code/Ticket Management System/ticket.c
  Source Code/Ticket Management System/user.c
Labels: feature

#78 Implement customer list tickets
  Source Code/Ticket Management System/customer_menu.c
Labels: feature

#83 Fixes & more sample data
  Example Database/Tickets.txt
  Example Database/Users.txt
  Source Code/Ticket Management System/supportgiver_menu.c
Labels: bug, feature

#81 Create some sample data
  Example Database/Explaination.txt
  Example Database/Tickets.txt
  Example Database/Users.txt
  Source Code/Ticket Management System/supportgiver_menu.c
Labels: feature

#82 Hebrew support removal //openSSL and LeanSQL and MSVC info Added
  Documentation & Design/design document.odt
  Requirements & Specifications/SRS v4.odt
Labels: documentation

#86 Media
  Example Database/Tickets.txt
  Source Code/Ticket Management System/customer_menu.c
  Source Code/Ticket Management System/supportgiver_menu.c
  Source Code/Ticket Management System/supportgiver_menu_util.c
  Source Code/Ticket Management System/supportgiver_menu_util.h
  Source Code/Ticket Management System/ticket.c
  Source Code/Ticket Management System/ticket.h
  Source Code/Ticket Management System/ticket_container.c
  Source Code/Ticket Management System/ticket_container_util.c
  Source Code/Ticket Management System/ticket_container_util.h
  Source Code/Ticket Management System/user_container.c
Labels: feature

#87 Analytical
  Requirements & Specifications/Prototype.pptx
  Source Code/Ticket Management System/supportgiver_menu.c
Labels: feature
