Repository SCE-SWE-2018-G3/ticket-management-system, pull requests merged in 2018-11, with the labels that each got.

#38 Changed DFD, SRS & prototype to accommodate the changes suggested
  Documentation & Design/DFD charts/DFD 2.dia
  Documentation & Design/DFD charts/DFD 2.png
  Documentation & Design/DFD charts/DFD 3.dia
  Documentation & Design/DFD charts/DFD 3.png
  Documentation & Design/DFD charts/DFD 4.dia
  Documentation & Design/DFD charts/DFD 4.png
  Documentation & Design/DFD charts/DFD 9.dia
  Documentation & Design/DFD charts/DFD 9.png
  Documentation & Design/DFD.dia
  Documentation & Design/DFD.png
  Documentation & Design/Use Case.dia
  Documentation & Design/Use Case.png
  Requirements & Specifications/Prototype.pptx
  Requirements & Specifications/SRS v3.odt
Labels: documentation, requested changes

#43 Various fixes
  Source Code/Ticket Management System/supportgiver_menu.c
  Source Code/Ticket Management System/ticket.c
  Source Code/Ticket Management System/ticket.h
  Source Code/Ticket Management System/ticket_container.c
Labels: bug, requested changes

#45 Change ticket ID generation logic
  Source Code/Ticket Management System/ticket.c
Labels: feature
